version: 1.0

# NOTE: RENAME THIS FILE FROM template_config.yaml TO config.yaml BEFORE USING

bot:
  token: Put Discord Token Here
AWS:
  Access: none
  Secret: none

Dynamo: # All the None values should be Strings in quotes
  ProgDB:
    TableName: None
    Endpoint: None
    Region: None
  RosterDB:
    TableName: None
    Endpoint: None
    Region: None
  MapDB:
    TableName: None
    Endpoint: None
    Region: None
  CountDB:
    TableName: None
    Endpoint: None
    Region: None

guild: put guild id here # Guild ID

presence_message: Make this what you want to say
morning: Good morning! # Message that the bot says in the morning channel at the designated time.
morning_channel: Put discord channel id here
officer_channel: Put discord channel id here
intro_channel: Put discord channel id here
# The welcome message can be as long as you want, and is very customizable.
welcome: |
  This is a very long message meant to welcome you to our very special discord channel where we all do things!
  And this is on a new line!
agree: Put a message here to DM to people when/if they agree to your rules

administration:
  rules: #Rules Channel ID
  private: # Private Channel ID
  general: # General channel ID
  reports: # Channel you want reports to go to, use same ID as private if you want
raids:
  category: # Category ID where you want new rosters created under
  lead: @everyone # Lead config is for the roles that are allowed to make new rosters.
  timezone: US/Central # NOTE: Use Python timezones from this package: https://pypi.org/project/pytz/
  roles: # Note: THE ROLES ARE CASE SENSITIVE
    base: @everyone # the base rank to join in on raids. If everyone use "@everyone"
    first: none
    second: none
    third: none
    fourth: none
  roster_defaults: # Sets the number of tanks, dps, and healers to open a roster with if none are set in the command
    tanks: 0
    dps: 0
    healers: 0
  dps_emoji: <:DPS:id> #Optional emoji use for rosters, make sure they are set in a server the bot is in. Example: <:Tank:933835838951948339>
  healer_emoji: <:Healer:id>
  tank_emoji: <:Tank:id>
roles:
  admin: Admin
  default: none # role everyone gets when joining, must exist in discord
  have_lock: false # If you want someone to use !agree and agree to rules before joining the server
  unlock: none # If have_lock is true, this will let people join the rest of the server
vanity: # You will have to add these yourself, the bot will handle the rest.
  type:
    <:Emoji_Name:Emoji_ID>: Role name in Discord

    

